// UI高速化・棚卸し再開対応版
const GAS_URL='https://script.google.com/macros/s/AKfycbzNpKApggyznTBt82xFHqlgCHYMM8ZMyxS0hf5N8L3kLqGiw6aktyMu1k9Bt2XZBEFS4w/exec';
let currentUser=null,itemCache=[],selectedStockItem=null,inventorySession=null,currentOrderContext=null;
const $=id=>document.getElementById(id);
async function callApi(action,payload={}){if(currentUser)payload.auth={email:currentUser.email};const r=await fetch(GAS_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload})});const j=await r.json();if(j.status==='error')throw new Error(j.message);return j}
function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]))}
function msg(t,e=false){const x=$('feedback-message');x.textContent=t;x.className=e?'error':'success';x.style.display='block';setTimeout(()=>x.style.display='none',4000)}
function showContent(id){document.querySelectorAll('.app-screen').forEach(x=>x.style.display='none');$(id).style.display='block'}
async function login(){try{const r=await callApi('login',{loginId:$('login-id').value.trim()});currentUser=r.data;sessionStorage.setItem('inventory_user',JSON.stringify(currentUser));$('login-screen').style.display='none';$('main-app').style.display='block';$('user-info').textContent=`${currentUser.name} (${currentUser.role})`;document.querySelectorAll('.admin-only').forEach(x=>x.style.display=currentUser.role==='管理者'?'block':'none');await loadItems();renderItems();loadInventory()}catch(e){$('login-error').textContent=e.message}}
async function loadItems(force=false){const k='inventory_items_v2',ts=Number(localStorage.getItem(k+'_ts')||0);if(!force&&Date.now()-ts<60000&&localStorage.getItem(k)){itemCache=JSON.parse(localStorage.getItem(k));return}const r=await callApi('get_item_list',{forceRefresh:force});itemCache=r.data||[];localStorage.setItem(k,JSON.stringify(itemCache));localStorage.setItem(k+'_ts',Date.now())}
function renderItems(){const q=($('item-search')?.value||'').toLowerCase();const box=$('item-list')||$('item-list-body');if(!box)return;const rows=itemCache.filter(i=>`${i.itemName} ${i.model}`.toLowerCase().includes(q));box.innerHTML=rows.map(i=>`<div class="item-card"><b>${esc(i.itemName)}</b> ${esc(i.model||'')}<div>在庫 ${i.stock} / 発注点 ${i.reorderPoint}</div>${Number(i.stock)<Number(i.reorderPoint)?`<button class="order-open" data-ref="${esc(i.itemRef)}">発注カードを開く</button>`:''}</div>`).join('');document.querySelectorAll('.order-open').forEach(b=>b.onclick=()=>openOrder(b.dataset.ref))}
function stockSearch(){const q=$('stock-item-search').value.toLowerCase();const box=$('stock-item-results');box.innerHTML=q?itemCache.filter(i=>`${i.itemName} ${i.model}`.toLowerCase().includes(q)).slice(0,20).map(i=>`<button data-ref="${esc(i.itemRef)}">${esc(i.itemName)} ${esc(i.model||'')}（在庫${i.stock}）</button>`).join(''):'';box.querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedStockItem=itemCache.find(i=>i.itemRef===b.dataset.ref);$('selected-stock-item').textContent=`${selectedStockItem.itemName} ${selectedStockItem.model||''} / 在庫 ${selectedStockItem.stock}`;$('selected-stock-item').style.display='block';box.innerHTML=''})}
async function stockUpdate(type){if(!selectedStockItem)return msg('物品を選択してください',true);try{const r=await callApi('stock_update',{itemRef:selectedStockItem.itemRef,itemName:selectedStockItem.itemName,model:selectedStockItem.model,type,quantity:Number($('stock-quantity').value)});msg(r.message);await loadItems(true);renderItems();if(r.orderRequired)showOrder(r.mailPreview,{historyId:r.historyId,...selectedStockItem})}catch(e){msg(e.message,true)}}
async function openOrder(ref){try{const i=itemCache.find(x=>x.itemRef===ref),r=await callApi('get_order_card',{itemRef:ref,itemName:i.itemName,model:i.model});showOrder(r.data,i)}catch(e){msg(e.message,true)}}
function showOrder(p,c){currentOrderContext=c;$('order-to').value=p.to||'';$('order-subject').value=p.subject||'';$('order-quantity').value=p.quantity||1;$('order-body').value=p.body||'';$('order-item-summary').textContent=`${c.itemName||''} ${c.model||''}`;$('order-dialog').showModal()}
async function sendOrder(){try{const r=await callApi('send_order',{...currentOrderContext,to:$('order-to').value,subject:$('order-subject').value,quantity:Number($('order-quantity').value),body:$('order-body').value});$('order-dialog').close();msg(r.message);await loadItems(true);renderItems()}catch(e){msg(e.message,true)}}
async function loadOrders(){try{const r=await callApi('get_order_history');$('order-history-list').innerHTML=(r.data||[]).map(x=>`<div class="order-card"><b>${esc(x.itemName)}</b> ${esc(x.model||'')}<div>${esc(x.orderDate)} / ${x.quantity}個 / ${esc(x.status)}</div>${x.status==='注文済み'?`<button class="cancel-order" data-id="${x.historyId}">キャンセル</button>`:''}</div>`).join('');document.querySelectorAll('.cancel-order').forEach(b=>b.onclick=()=>cancelOrder(Number(b.dataset.id)))}catch(e){msg(e.message,true)}}
async function cancelOrder(id){if(!confirm('発注をキャンセルしますか？'))return;try{const r=await callApi('cancel_order',{historyId:id});msg(r.message);loadOrders();await loadItems(true);renderItems()}catch(e){msg(e.message,true)}}
async function loadInventory(){try{const r=await callApi('get_active_inventory');inventorySession=r.data;$('inventory-empty').style.display=inventorySession?'none':'block';$('inventory-active').style.display=inventorySession?'block':'none';if(inventorySession)renderInventory()}catch(e){msg(e.message,true)}}
async function startInventory(){try{const r=await callApi('start_inventory');inventorySession=r.data;$('inventory-empty').style.display='none';$('inventory-active').style.display='block';renderInventory()}catch(e){msg(e.message,true)}}
let invFilter='unchecked';function renderInventory(){const q=($('inventory-search')?.value||'').toLowerCase(),a=inventorySession.items||[],done=a.filter(x=>x.checked).length,diff=a.filter(x=>x.checked&&Number(x.difference)!==0).length;$('inventory-progress-text').textContent=`${done} / ${a.length}`;$('inventory-diff-count').textContent=`差異 ${diff}`;let rows=a.filter(x=>`${x.itemName} ${x.model}`.toLowerCase().includes(q));if(invFilter==='unchecked')rows=rows.filter(x=>!x.checked);if(invFilter==='diff')rows=rows.filter(x=>x.checked&&Number(x.difference)!==0);$('inventory-list').innerHTML=rows.map(x=>`<div class="inventory-card"><b>${esc(x.itemName)}</b> ${esc(x.model||'')}<div>システム在庫 ${x.expectedStock} ${x.checked?`/ 差異 ${x.difference}`:''}</div><input class="actual" data-ref="${esc(x.itemRef)}" type="number" min="0" value="${x.checked?x.actualStock:''}"><button class="save-inv" data-ref="${esc(x.itemRef)}">${x.checked?'更新':'確定'}</button></div>`).join('');document.querySelectorAll('.save-inv').forEach(b=>b.onclick=()=>saveInv(b.dataset.ref))}
async function saveInv(ref){const inp=document.querySelector(`.actual[data-ref="${CSS.escape(ref)}"]`),item=inventorySession.items.find(x=>x.itemRef===ref);try{const r=await callApi('save_inventory_item',{sessionId:inventorySession.sessionId,itemRef:ref,itemName:item.itemName,model:item.model,actualStock:Number(inp.value)});Object.assign(item,r.data);renderInventory()}catch(e){msg(e.message,true)}}
async function completeInventory(){try{const r=await callApi('complete_inventory',{sessionId:inventorySession.sessionId});msg(r.message);inventorySession=null;await loadItems(true);renderItems();loadInventory()}catch(e){msg(e.message,true)}}
async function registerItem(){try{const r=await callApi('item_register',{itemName:$('reg-item-name').value.trim(),model:$('reg-model').value.trim(),stock:Number($('reg-stock').value),reorderPoint:Number($('reg-reorder-point').value),parLevel:Number($('reg-par-level').value),price:Number($('reg-price').value),supplierEmail:$('reg-supplier').value.trim()});msg(r.message);await loadItems(true);renderItems()}catch(e){msg(e.message,true)}}
document.addEventListener('DOMContentLoaded',async()=>{const s=sessionStorage.getItem('inventory_user');if(s){currentUser=JSON.parse(s);$('login-screen').style.display='none';$('main-app').style.display='block';$('user-info').textContent=`${currentUser.name} (${currentUser.role})`;await loadItems();renderItems();loadInventory()}});
$('login-btn').onclick=login;$('logout-btn').onclick=()=>{sessionStorage.clear();location.reload()};$('main-menu').onclick=e=>{if(!e.target.dataset.screen)return;showContent(e.target.dataset.screen);if(e.target.dataset.screen==='order-history-screen')loadOrders();if(e.target.dataset.screen==='inventory-screen')loadInventory()};if($('item-search'))$('item-search').oninput=renderItems;$('refresh-list-btn').onclick=async()=>{await loadItems(true);renderItems()};$('stock-item-search').oninput=stockSearch;$('stock-in-btn').onclick=()=>stockUpdate('入庫');$('stock-out-btn').onclick=()=>stockUpdate('出庫');$('send-order-btn').onclick=sendOrder;$('refresh-order-history-btn').onclick=loadOrders;$('start-inventory-btn').onclick=startInventory;$('refresh-inventory-btn').onclick=loadInventory;$('inventory-search').oninput=renderInventory;$('show-unchecked-btn').onclick=()=>{invFilter='unchecked';renderInventory()};$('show-diff-btn').onclick=()=>{invFilter='diff';renderInventory()};$('show-all-inventory-btn').onclick=()=>{invFilter='all';renderInventory()};$('complete-inventory-btn').onclick=completeInventory;$('register-item-btn').onclick=registerItem;
