/** 在庫管理アプリ backend 2026-09 */
const SPREADSHEET_ID='10llRezExCXTM9XpXCKP3vp3tbmmTO3Q_Xrgm2n5jsH8';
const ss=SpreadsheetApp.openById(SPREADSHEET_ID);
const SHEET_USERS='ユーザー管理',SHEET_ITEM_MASTER='物品マスター',SHEET_HISTORY='入出庫履歴',SHEET_SETTINGS='設定',SHEET_DEPARTMENTS='部署マスター',SHEET_SUPPLIERS='発注先マスター',SHEET_ORDER_LOG='発注・キャンセル履歴',SHEET_INVENTORY='棚卸しセッション';
const ROLES={ADMIN:'管理者',USER:'使用者'};
const COL_USERS={EMAIL:1,NAME:2,HOSPITAL:3,DEPARTMENT:4,ROLE:5,LOGIN_ID:6,PHS:7};
const COL_INVENTORY={QR_ID:1,BARCODE:2,ITEM_NAME:3,MODEL:4,STOCK:5,REORDER_POINT:6,SUPPLIER_EMAIL:7,PRICE:8,PAR_LEVEL:9,ORDERED_QUANTITY:10,IS_DELETED:11};
const COL_HISTORY={TIMESTAMP:1,ITEM_KEY:2,TYPE:3,QUANTITY:4,USER_EMAIL:5,DEPARTMENT:6,PHS:7,ORDER_STATUS:8,ORDER_MAIL_ID:9};
const INV={SESSION_ID:1,STATUS:2,USER_EMAIL:3,STARTED_AT:4,UPDATED_AT:5,COMPLETED_AT:6,ITEM_REF:7,ITEM_NAME:8,MODEL:9,EXPECTED_STOCK:10,ACTUAL_STOCK:11,DIFFERENCE:12,CHECKED_AT:13};
function doGet(){return HtmlService.createHtmlOutput('<h2>Backend is running</h2>')}
function doPost(e){try{const req=JSON.parse(e.postData.contents||'{}'),a=req.action,p=req.payload||{};if(a==='login')return j(authUser(p));let u=getUser(p.auth);if(a==='get_item_list')return j(getItems(p));if(a==='get_order_history')return j(getOrders(u));if(a==='get_order_card')return j(getOrderCard({...p,user:u}));if(a==='get_active_inventory')return j(getActiveInventory(u));const lock=LockService.getScriptLock();lock.waitLock(15000);try{if(a==='stock_update')return j(stock({...p,user:u}));if(a==='send_order')return j(sendOrder({...p,user:u}));if(a==='cancel_order')return j(cancelOrder({...p,user:u}));if(a==='start_inventory')return j(startInventory(u));if(a==='save_inventory_item')return j(saveInventory({...p,user:u}));if(a==='complete_inventory')return j(completeInventory({...p,user:u}));if(a==='item_register'){if(u.role!==ROLES.ADMIN)throw Error('管理者権限が必要です。');return j(registerItem({...p,user:u}))}return j({status:'error',message:'無効なアクションです。'})}finally{try{lock.releaseLock()}catch(_){}}}catch(err){return j({status:'error',message:err.message||String(err)})}}
function authUser(a){if(!a||(!a.loginId&&!a.email))return{status:'error',data:{isAuthorized:false},message:'認証情報がありません。'};const sh=ss.getSheetByName(SHEET_USERS),rows=sh.getLastRow()>1?sh.getRange(2,1,sh.getLastRow()-1,7).getValues():[];for(const r of rows){if((a.loginId&&String(r[5])===String(a.loginId))||(a.email&&String(r[0]).toLowerCase()===String(a.email).toLowerCase()))return{status:'success',data:{isAuthorized:true,email:r[0],name:r[1],hospital:r[2],department:r[3],role:r[4],loginId:r[5],phs:r[6]}}}return{status:'error',data:{isAuthorized:false},message:'ログイン情報が見つかりません。'}}
function getUser(a){const r=authUser(a);if(r.status!=='success'||!r.data.isAuthorized)throw Error('認証に失敗しました。');return r.data}
function getItems(p){if(p&&p.forceRefresh)CacheService.getScriptCache().remove('items_v3');return{status:'success',data:itemRecords()}}
function itemRecords(){const c=CacheService.getScriptCache(),hit=c.get('items_v3');if(hit)return JSON.parse(hit);const sh=ss.getSheetByName(SHEET_ITEM_MASTER),last=sh.getLastRow();if(last<2)return[];const rows=sh.getRange(2,1,last-1,Math.max(sh.getLastColumn(),11)).getValues(),out=[];rows.forEach((r,i)=>{if(r[10])return;out.push({itemRef:'R:'+(i+2),itemName:r[2]||'',model:r[3]||'',stock:Number(r[4]||0),reorderPoint:Number(r[5]||0),supplierEmail:r[6]||'',price:Number(r[7]||0),parLevel:Number(r[8]||0),orderedQuantity:Number(r[9]||0)})});c.put('items_v3',JSON.stringify(out),60);return out}
function clearItems(){CacheService.getScriptCache().remove('items_v3')}
function resolveRow(p){const sh=ss.getSheetByName(SHEET_ITEM_MASTER),ref=String(p.itemRef||'');if(/^R:\d+$/.test(ref)){const row=Number(ref.slice(2));if(row>=2&&row<=sh.getLastRow()){const v=sh.getRange(row,1,1,Math.max(sh.getLastColumn(),11)).getValues()[0];if(!v[10]&&(!p.itemName||String(v[2])===String(p.itemName))&&(!p.model||String(v[3])===String(p.model)))return row}}const name=String(p.itemName||''),model=String(p.model||'');if(name){const rows=sh.getRange(2,1,Math.max(0,sh.getLastRow()-1),Math.max(sh.getLastColumn(),11)).getValues();for(let i=0;i<rows.length;i++)if(!rows[i][10]&&String(rows[i][2])===name&&String(rows[i][3])===model)return i+2}return-1}
function rowFromKey(key){const s=String(key||'');if(/^R:\d+$/.test(s))return Number(s.slice(2));const sh=ss.getSheetByName(SHEET_ITEM_MASTER),last=sh.getLastRow();if(last<2)return-1;const rows=sh.getRange(2,1,last-1,2).getDisplayValues();for(let i=0;i<rows.length;i++){const q=String(rows[i][0]||'').split(',').map(x=>x.trim());if(q.includes(s)||String(rows[i][1]||'').trim()===s)return i+2}return-1}
function stock(p){const row=resolveRow(p);if(row<2)throw Error('対象の物品が見つかりません。');const is=ss.getSheetByName(SHEET_ITEM_MASTER),hs=ss.getSheetByName(SHEET_HISTORY),r=is.getRange(row,1,1,Math.max(is.getLastColumn(),11)).getValues()[0],qty=Number(p.quantity||0);if(qty<=0)throw Error('数量を確認してください。');const next=Number(r[4]||0)+(p.type==='入庫'?qty:-qty);if(next<0)throw Error('在庫数がマイナスになるため処理できません。');is.getRange(row,5).setValue(next);if(p.type==='入庫'){const c=is.getRange(row,10);c.setValue(Math.max(0,Number(c.getValue()||0)-qty))}hs.appendRow([new Date(),'R:'+row,p.type,qty,p.user.email,p.user.department||'',p.user.phs||'','','']);const hid=hs.getLastRow();clearItems();const reorder=Number(r[5]||0);if(p.type==='出庫'&&next<reorder){const par=Number(r[8]||0),oq=Math.max(1,(par>next?par-next:reorder-next));return{status:'success',message:'在庫を更新しました。発注が必要です。',orderRequired:true,mailPreview:orderPreview(r,oq,p.user),historyId:hid}}return{status:'success',message:'在庫を更新しました。'}}
function getOrderCard(p){const row=resolveRow(p);if(row<2)throw Error('対象の物品が見つかりません。');const sh=ss.getSheetByName(SHEET_ITEM_MASTER),r=sh.getRange(row,1,1,Math.max(sh.getLastColumn(),11)).getValues()[0],stock=Number(r[4]||0),reorder=Number(r[5]||0),par=Number(r[8]||0),ordered=Number(r[9]||0),qty=Math.max(1,(par||reorder)-stock-ordered);return{status:'success',data:{...orderPreview(r,qty,p.user),itemName:r[2],model:r[3]}}}
function sendOrder(p){const is=ss.getSheetByName(SHEET_ITEM_MASTER),hs=ss.getSheetByName(SHEET_HISTORY),os=ss.getSheetByName(SHEET_ORDER_LOG);let row=-1,hid=Number(p.historyId||0);if(hid>=2&&hid<=hs.getLastRow())row=rowFromKey(hs.getRange(hid,2).getValue());if(row<2)row=resolveRow(p);if(row<2)throw Error('発注対象の物品が見つかりません。');const qty=Number(p.quantity||0),item=is.getRange(row,1,1,Math.max(is.getLastColumn(),11)).getValues()[0];if(!hid){hs.appendRow([new Date(),'R:'+row,'発注',qty,p.user.email,p.user.department||'',p.user.phs||'','','']);hid=hs.getLastRow()}else hs.getRange(hid,4).setValue(qty);const oc=is.getRange(row,10);oc.setValue(Number(oc.getValue()||0)+qty);const m=GmailApp.createDraft(p.to,p.subject,p.body).send(),mid=m.getId();admins().forEach(x=>GmailApp.sendEmail(x,'[転送：発注] '+p.subject,'',{htmlBody:String(p.body).replace(/\n/g,'<br>')}));hs.getRange(hid,8).setValue('注文済み');hs.getRange(hid,9).setValue(mid);os.appendRow([new Date(),'発注',item[2],item[3],qty,p.user.name,mid]);clearItems();return{status:'success',message:'発注メールを送信しました。',mailId:mid}}
function getOrders(u){const hs=ss.getSheetByName(SHEET_HISTORY),is=ss.getSheetByName(SHEET_ITEM_MASTER),last=hs.getLastRow();if(last<2)return{status:'success',data:[]};const rows=hs.getRange(2,1,last-1,Math.max(hs.getLastColumn(),9)).getValues(),out=[];rows.forEach((r,i)=>{if(!['注文済み','キャンセル済み'].includes(r[7]))return;if(u.role===ROLES.USER&&String(r[4])!==String(u.email))return;const row=rowFromKey(r[1]);let name='不明な物品',model='';if(row>=2){const it=is.getRange(row,1,1,Math.max(is.getLastColumn(),11)).getValues()[0];name=it[2]||name;model=it[3]||''}out.push({historyId:i+2,mailId:r[8],itemName:name,model,orderDate:Utilities.formatDate(new Date(r[0]),'Asia/Tokyo','yyyy/MM/dd'),quantity:r[3],status:r[7]})});out.reverse();return{status:'success',data:out}}
function cancelOrder(p){const hs=ss.getSheetByName(SHEET_HISTORY),is=ss.getSheetByName(SHEET_ITEM_MASTER),os=ss.getSheetByName(SHEET_ORDER_LOG),id=Number(p.historyId),h=hs.getRange(id,1,1,Math.max(hs.getLastColumn(),9)).getValues()[0],row=rowFromKey(h[1]);if(row<2)throw Error('物品が見つかりません。');const item=is.getRange(row,1,1,Math.max(is.getLastColumn(),11)).getValues()[0],qty=Number(h[3]||0),oc=is.getRange(row,10);oc.setValue(Math.max(0,Number(oc.getValue()||0)-qty));const s=supplier(item[6]),sub='【注文キャンセルのお願い】'+item[2],body=cancelBody(item,qty,p.user);GmailApp.sendEmail(s.email,sub,body);admins().forEach(x=>GmailApp.sendEmail(x,'[転送：キャンセル] '+sub,'',{htmlBody:body.replace(/\n/g,'<br>')}));os.appendRow([new Date(),'キャンセル',item[2],item[3],qty,p.user.name,h[8]||'']);hs.getRange(id,8).setValue('キャンセル済み');clearItems();return{status:'success',message:'キャンセルメールを送信しました。'}}
function invSheet(){let sh=ss.getSheetByName(SHEET_INVENTORY);if(!sh){sh=ss.insertSheet(SHEET_INVENTORY);sh.getRange(1,1,1,13).setValues([['session_id','status','user_email','started_at','updated_at','completed_at','item_ref','item_name','model','expected_stock','actual_stock','difference','checked_at']])}return sh}
function startInventory(u){const a=getActiveInventory(u).data;if(a)return{status:'success',data:a};const items=itemRecords(),sh=invSheet(),id='INV-'+Utilities.formatDate(new Date(),'Asia/Tokyo','yyyyMMdd-HHmmss')+'-'+String(u.email).slice(0,20),now=new Date(),rows=items.map(i=>[id,'進行中',u.email,now,now,'',i.itemRef,i.itemName,i.model,i.stock,'','','']);if(rows.length)sh.getRange(sh.getLastRow()+1,1,rows.length,13).setValues(rows);return{status:'success',data:{sessionId:id,status:'進行中',items:rows.map(invObj)}}}
function getActiveInventory(u){const sh=invSheet(),last=sh.getLastRow();if(last<2)return{status:'success',data:null};const rows=sh.getRange(2,1,last-1,13).getValues();let id='';for(let i=rows.length-1;i>=0;i--)if(String(rows[i][2])===String(u.email)&&rows[i][1]==='進行中'){id=rows[i][0];break}if(!id)return{status:'success',data:null};const a=rows.filter(r=>r[0]===id);return{status:'success',data:{sessionId:id,status:'進行中',items:a.map(invObj)}}}
function invObj(r){const checked=!!r[12];return{itemRef:r[6],itemName:r[7],model:r[8],expectedStock:Number(r[9]||0),actualStock:checked?Number(r[10]||0):'',difference:checked?Number(r[11]||0):0,checked}}
function saveInventory(p){const sh=invSheet(),rows=sh.getRange(2,1,sh.getLastRow()-1,13).getValues(),actual=Number(p.actualStock);for(let i=0;i<rows.length;i++){const r=rows[i];if(r[0]===p.sessionId&&r[6]===p.itemRef){if(String(r[2])!==String(p.user.email))throw Error('編集権限がありません。');const exp=Number(r[9]||0),now=new Date();sh.getRange(i+2,5).setValue(now);sh.getRange(i+2,11,1,3).setValues([[actual,actual-exp,now]]);return{status:'success',data:{itemRef:p.itemRef,itemName:r[7],model:r[8],expectedStock:exp,actualStock:actual,difference:actual-exp,checked:true}}}}throw Error('棚卸し対象が見つかりません。')}
function completeInventory(p){const sh=invSheet(),rows=sh.getRange(2,1,sh.getLastRow()-1,13).getValues(),is=ss.getSheetByName(SHEET_ITEM_MASTER),hs=ss.getSheetByName(SHEET_HISTORY),logs=[];let checked=0,changed=0;rows.forEach((r,i)=>{if(r[0]!==p.sessionId)return;if(r[12]){checked++;const actual=Number(r[10]||0),exp=Number(r[9]||0),row=resolveRow({itemRef:r[6],itemName:r[7],model:r[8]});if(row>=2&&actual!==exp){is.getRange(row,5).setValue(actual);changed++;logs.push([new Date(),'R:'+row,'棚卸修正',actual,p.user.email,p.user.department||'',p.user.phs||'','',''])}}sh.getRange(i+2,2).setValue('完了');sh.getRange(i+2,6).setValue(new Date())});if(logs.length)hs.getRange(hs.getLastRow()+1,1,logs.length,9).setValues(logs);clearItems();return{status:'success',message:`棚卸しを完了しました（確認 ${checked}件 / 在庫修正 ${changed}件）。`}}
function registerItem(p){if(!String(p.itemName||'').trim())throw Error('物品名は必須です。');const sh=ss.getSheetByName(SHEET_ITEM_MASTER);sh.appendRow(['','',p.itemName,p.model||'',Number(p.stock||0),Number(p.reorderPoint||0),p.supplierEmail||'',Number(p.price||0),Number(p.parLevel||0),0,false]);const row=sh.getLastRow();ss.getSheetByName(SHEET_HISTORY).appendRow([new Date(),'R:'+row,'新規登録',Number(p.stock||0),p.user.email,p.user.department||'',p.user.phs||'','','']);clearItems();return{status:'success',message:`「${p.itemName}」を新規登録しました。`}}
function orderPreview(r,qty,u){const sh=ss.getSheetByName(SHEET_SETTINGS),st=sh.getRange('B1').getValue(),bt=sh.getRange('B2').getValue(),s=supplier(r[6]),price=Number(r[7]||0),sub=price*qty;return{to:s.email,subject:String(st).replace(/{{物品名}}/g,r[2]).replace(/{{発注者名}}/g,u.name||''),body:String(bt).replace(/{{会社名}}/g,s.companyName||'ご担当者様').replace(/{{担当者名}}/g,s.contactName?s.contactName+' 様':'').replace(/{{物品名}}/g,r[2]).replace(/{{型番}}/g,r[3]||'').replace(/{{数量}}/g,qty).replace(/{{単価}}/g,price.toLocaleString()+'円').replace(/{{小計}}/g,sub.toLocaleString()+'円').replace(/{{合計金額}}/g,sub.toLocaleString()+'円').replace(/{{病院名}}/g,u.hospital||'').replace(/{{部署名}}/g,u.department||'').replace(/{{発注者名}}/g,u.name||'').replace(/{{発注者メールアドレス}}/g,u.email||''),quantity:qty,price,subtotal:sub}}
function cancelBody(r,qty,u){const t=ss.getSheetByName(SHEET_SETTINGS).getRange('B3').getValue(),price=Number(r[7]||0);return String(t).replace(/{{物品名}}/g,r[2]).replace(/{{型番}}/g,r[3]||'').replace(/{{数量}}/g,qty).replace(/{{単価}}/g,price.toLocaleString()+'円').replace(/{{合計金額}}/g,(price*qty).toLocaleString()+'円').replace(/{{病院名}}/g,u.hospital||'').replace(/{{部署名}}/g,u.department||'').replace(/{{発注者名}}/g,u.name||'').replace(/{{発注者メールアドレス}}/g,u.email||'')}
function supplier(email){const sh=ss.getSheetByName(SHEET_SUPPLIERS),last=sh.getLastRow();if(last<2)return{email,companyName:'',contactName:''};const rows=sh.getRange(2,1,last-1,Math.max(sh.getLastColumn(),3)).getValues(),t=String(email||'').toLowerCase();for(const r of rows)if(String(r[0]||'').toLowerCase()===t)return{email:r[0],companyName:r[1],contactName:r[2]};return{email,companyName:'',contactName:''}}
function admins(){const sh=ss.getSheetByName(SHEET_USERS),rows=sh.getLastRow()>1?sh.getRange(2,1,sh.getLastRow()-1,5).getValues():[];return rows.filter(r=>r[4]==='管理者').map(r=>r[0]).filter(Boolean)}
function j(o){return ContentService.createTextOutput(JSON.stringify(o||{})).setMimeType(ContentService.MimeType.JSON)}
